### ISSUE TITLE
there is a typo WthdrawlType = > WithdrawlType

### ISSUE THREAD

**Issue by treping** [leosdibella/WePay.NET#3]
https://github.com/leosdibella/WePay.NET/blob/master/WePay.NET/Account/Structure/Balances.cs#L53
there is a typo WthdrawlType = > WithdrawlType

**Comment by leosdibella** [comment]
Oh man, there's a bunch of typos in there, Withdrawl should be Withdrawal :(

I'll get a fix for this out there ASAP, sorry!!

**Comment by leosdibella** [comment]
Package updated! Check for version 1.0.5.11. Thanks for finding this! :)

**Comment by treping** [comment]
you save tremendous time already with this lib so don't worry 
Cheers!
